### ISSUE TITLE
Are some models reporting values in PgC while others are reporting in PgCO2?

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/willC#2]
I've been playing around with the global rh monthly fluxes for the "willC" and I suspect that some models may report the values in Pg C while other models are reporting values in Pg of CO2. (This could also explain why the E3SM GPP seemed abnormally large). @bpbond I would appreciate your more expert opinion on this, I am not familiar enough with rh to have a good sense of units. 

This is what I get when I look at the total fluxes for a single decade. Both `CNRM-CM6-1` and `CNRM-CM6-1-HR` seem pretty high to me. 
![image](https://user-images.githubusercontent.com/27299759/76450918-fa19c280-63a4-11ea-9414-eebe22c7a36f.png)

If I convert the data from `CNRM-CM6-1` and `CNRM-CM6-1-HR` Pg CO2 to PgC I think the results look better... what are you thoughts? 

![image](https://user-images.githubusercontent.com/27299759/76451058-39e0aa00-63a5-11ea-9b65-17752fee0bf8.png)

**Comment by bpbond** [comment]
It's certainly possible (but it'd be a mistake), and I agree that the discrepancy is in the right range.

What are those y axis units? PgC per...day?

**Comment by kdorheim** [comment]
PgC per month. 

So would we want to convert those time series or exclude them from the analysis?

**Comment by bpbond** [comment]
>PgC per month

Those are really low values in that case. Hmm. A global flux averaging 0.08 PgC/month = 1 Pg/yr which isn't possible. But if that's the per-month flux _per day_, i.e. we need to sum over the month, then we're looking at ~29 PgC which is low but at least not laughable.

**Comment by kdorheim** [comment]
Dang good catch! I took a look at the function I was using  to convert from a per second flux to the monthly flux and there was an error so it was calculating the per hour flux... (major face palm) how does this look? 

![image](https://user-images.githubusercontent.com/27299759/76523877-87115a00-643f-11ea-963f-b79ddd379787.png)

**Comment by bpbond** [comment]
@kdorheim hahaha we can all do that. Glad you found it! Ah yes, those numbers look _much_ better. 👍

**Comment by kdorheim** [comment]
haha @bpbond this is a GREAT example why being able to run a model or process model output is not great if you don't have a sense of the units and also why using functions is V important! It's easier to pick out an error / solve a bug if it is consistently incorrect and also unit testing.

**Comment by kdorheim** [comment]
hmm... I wanted to check to see if it was obvious in the meta data if some of the output files were being reported in gC or gCO2. It is unclear, it seems like quite a few of the files use a both carbon and carbon dioxide... 🙀we will figure it out I think that we can table this for now but may have to rely on expert judgement. 

This is the file with the total flux that is too high 
``` 
File rh_Lmon_CNRM-CM6-1_historical_r4i1p1f2_gr_185001-201412.nc (NC_FORMAT_NETCDF4):

     2 variables (excluding dimension variables):
        double time_bounds[axis_nbounds,time]   (Chunking: [2,1])  
        float rh[lon,lat,time]   (Chunking: [256,128,1])  (Compression: shuffle,level 4)
            long_name: Carbon Mass Flux into Atmosphere due to Heterotrophic Respiration on Land
            units: kg m-2 s-1
            online_operation: average
            cell_methods: area: mean where land time: mean
            interval_operation: 900 s
            interval_write: 1 month
            _FillValue: 1.00000002004088e+20
            missing_value: 1.00000002004088e+20
            coordinates: 
            description: Carbon Mass Flux into Atmosphere due to Heterotrophic Respiration on Land
            positive: up
            history: none
            cell_measures: area: areacella
            standard_name: surface_upward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_heterotrophic_respiration
```
The next two are meta data from files that were "normal".
```
File rh_Lmon_CESM2-FV2_historical_r1i1p1f1_gn_190001-194912.nc (NC_FORMAT_NETCDF4):

     4 variables (excluding dimension variables):
        float rh[lon,lat,time]   (Chunking: [144,96,1])  (Compression: shuffle,level 2)
            _FillValue: 1.00000002004088e+20
            cell_measures: area: areacella
            cell_methods: area: mean where land time: mean
            comment: chunits(HR, units="g m-2 s-1")
            coordinates: time lat lon
            description: Carbon mass flux per unit area into atmosphere due to heterotrophic respiration on land (respiration by consumers)
            frequency: mon
            id: rh
            long_name: Total Heterotrophic Respiration on Land as Carbon Mass Flux [kgC m-2 s-1]
            mipTable: Lmon
            missing_value: 1e+20
            out_name: rh
            positive: up
            prov: Lmon ((isd.003))
            realm: land
            standard_name: surface_upward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_heterotrophic_respiration
            time: time
            time_label: time-mean
            time_title: Temporal mean
            title: Total Heterotrophic Respiration on Land as Carbon Mass Flux [kgC m-2 s-1]
```

```
File rh_Lmon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc (NC_FORMAT_NETCDF4_CLASSIC):

     4 variables (excluding dimension variables):
        double time_bnds[bnds,time]   
        double lat_bnds[bnds,lat]   
        double lon_bnds[bnds,lon]   
        float rh[lon,lat,time]   
            standard_name: surface_upward_mass_flux_of_carbon_dioxide_expressed_as_carbon_due_to_heterotrophic_respiration
            long_name: Carbon Mass Flux into Atmosphere Due to Heterotrophic Respiration on Land
            comment: Carbon mass flux per unit area into atmosphere due to heterotrophic respiration on land (respiration by consumers)
            units: kg m-2 s-1
            cell_methods: area: mean where land time: mean
            cell_measures: area: areacella
            history: 2019-11-15T13:52:26Z altered by CMOR: replaced missing value flag (-1.07374e+09) with standard missing value (1e+20).
            missing_value: 1.00000002004088e+20
            _FillValue: 1.00000002004088e+20
```
